//THIS WIN96 VIRUS WAS 8 DAYS IN THE MAKING AND I FEEL AS IT IS COMPLETE
//DO NOT RUN THIS ON YOUR WINDOWS 96 MACHINE WITHOUT BACKING UP IMPORTANT DATA!!!
//VIRUS ALL CODED BY SMG200

//PAYLOADS 
// 05/01
// 05/04
// 05/11
// 05/18

//IF YOU ARE GOING TO USE MY CODE FOR YOUR PROJECTS OR ANYTHING LIKE THAT
//DONT BE A SKID AND CREDIT ME PLEASE AND THANK YOU.

//NAME: MOWER
//SIZE: 16KILOBYTES
//SUPPORTED VERSIONS: 3.2.3

//<3
